name: Check XML files in PR

on: [pull_request]

jobs:
  check-xml-files:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: pip install requests

      - name: Check XML files in PR
        env:
          PULL_REQUEST_URL: ${{ github.event.pull_request.html_url }}
          #SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: python xml_check2.py
