name: 更新内容にxmlファイルが含まれているか確認

on: [pull_request]

jobs:
  xml_check:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x
      
    - name: Install requests library
      run: pip install requests
      
    - name: Install slack-sdk library
      run: pip install slack-sdk
      
    - name: Check XML change
      run: python xml_check.py
      env:
        GITHUB_API_URL: ${{ github.api_url }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        PR_NUMBER: ${{ github.event.number }}
        SLACK_BOT_TOKEN: xoxb-3321671539026-5017684223201-3XDKf5TB2OEpOcTxQAh1nwJC
        SLACK_CHANNEL: #xml更新監視所
