name: 更新内容にxmlファイルが含まれているか確認

on: [pull_request]

jobs:
  xml_check:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x
      
    - name: Install requests library
      run: pip install requests
      
    - name: Install slack-sdk library
      run: pip install slack-sdk
      
    - name: Install PyGithub
      run: pip install PyGithub
      
    - name: Check XML change
      run: |
        repo_url=${{ github.repository }}
        csv_file="reviewers_test.csv"
        csv_url="https://raw.githubusercontent.com/$repo_url/develop/$csv_file"
        echo "CSV URL: $csv_url"
        wget $csv_url
        python xml_check.py
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_API_URL: ${{ github.api_url }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        PR_NUMBER: ${{ github.event.number }}
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        SLACK_CHANNEL: "#xml更新監視所"
