name: 更新内容にxmlファイルが含まれているか確認

on: [pull_request]

jobs:
  xml_check:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GITHUB_API_URL: ${{ github.api_url }}
      GITHUB_REPOSITORY: ${{ github.repository }}
      PR_NUMBER: ${{ github.event.number }}
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      SLACK_CHANNEL: "#xml更新監視所"

    steps:
    - name: Checkout code
      uses: actions/checkout@v2.4.3
      
    - name: Setup Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2.4.2
      with:
        python-version: ${{ matrix.python-version }}
      
    - name: Install requests library
      run: pip install requests
      
    - name: Install slack-sdk library
      run: pip install slack-sdk
      
    - name: Install PyGithub
      run: pip install PyGithub
      
    - name: Download csv
      run: |
        repo_url=${{ github.repository }}
        csv_file="reviewers.csv"
        csv_url="https://raw.githubusercontent.com/$repo_url/develop/$csv_file"
        echo "CSV URL: $csv_url"
        wget $csv_url
        
    - name: Check XML change
      run: |
        python xml_check.py
